# This is a parameters file
# It is written according to the YAML-convention (www.yaml.org) and is checked by the code for consistency.
# It has been adopted from https://github.com/AIM-Harvard/pyradiomics/blob/master/examples/exampleSettings/Params.yaml
# 
# There are three parameter categories:
# - setting: Setting to use for preprocessing and class specific settings. if no <value> is specified, the value for
#   this setting is set to None.
# - featureClass: Feature class to enable, <value> is list of strings representing enabled features. If no <value> is
#   specified or <value> is an empty list ('[]'), all features for this class are enabled.
# - imageType: image types to calculate features on. <value> is custom kwarg settings (dictionary). if <value> is an
#   empty dictionary ('{}'), no custom settings are added for this input image.
#
# 

# Settings used.
setting:
  normalize: true
  binCount: 64
  interpolator: 'sitkBSpline' # This is an enumerated value, here None is not allowed
  resampledPixelSpacing: [0.9, 0.9, 3.0] # To enable it, specify spacing in x, y, z as [x, y , z]
  voxelArrayShift: 300

# Image types used: "Original" for unfiltered image, LoG and Wavelet filtered images.
imageType:
   Original: {}
   LoG:
     sigma: [3.0, 4.0, 5.0]
   Wavelet: {}

# Featureclasses, from which features must be calculated. If a featureclass is not mentioned, no features are calculated
# for that class. Otherwise, the specified features are calculated, or, if none are specified, all are calculated (excluding redundant/deprecated features).
featureClass:
  firstorder: 
  shape: 
  glcm:
  glrlm:
  glszm:
  gldm:
  ngtdm:
